version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"